version: "3.8"

services:
  frontend:
    build:
      context: ./iks-rag-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./iks-rag-pipelines
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
